apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "namer-inator.fullname" . }}
  labels:
    {{- include "namer-inator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "namer-inator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "namer-inator.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "namer-inator.name" . }}
          image: "{{ .Values.image.repository }}/{{ include "namer-inator.name" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /random-inator
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /random-inator
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
